// <auto-generated />
namespace AI_TaskM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class maintask15 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(maintask15));
        
        string IMigrationMetadata.Id
        {
            get { return "202207071323500_maintask15"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
